apiVersion: v1
kind: Secret
metadata:
  name: porkbun-dns-credentials
  namespace: default
type: Opaque
data:
  PORKBUN_API_KEY: cGsxXzlmZDJlOGRmMTAyMzY0ZDEzZDg5ODNmNzllOTQxZjQwODQwYWJkZTcwMDc0ZTJkOWUyMjY3ZDdkMGE5MmFhMWI=
  PORKBUN_SECRET_API_KEY: c2sxXzUyZmIyMTlkMGMzNmViOGYyOWI0ZDkzMDA0MDNmNGE4N2QxN2IzMDkzN2Q4MWQ1ZmIxYzEyOTZjYTcwNjYyMTc=

