apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frp

resources:
  - namespace.yaml
  - secrets.yaml
  - plugin-secrets.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - middleware.yaml

commonLabels:
  app.kubernetes.io/name: frps
  app.kubernetes.io/component: tunnel-server
  app.kubernetes.io/part-of: lum-tools
