apiVersion: v1
kind: Secret
metadata:
  name: frp-plugin-config
  namespace: frp
type: Opaque
stringData:
  config.json: |
    {
      "platform_url": "http://platform-service.platform.svc.cluster.local",
      "platform_internal_secret": "83503ad414c5fee1908e273de5f0f16ad74ed70a5a457db7672e99cc86809654",
      "cache_ttl_seconds": 300,
      "traffic_report_interval_seconds": 300,
      "log_level": "debug",
      "frp_dashboard_url": "http://127.0.0.1:7400",
      "frp_dashboard_user": "admin",
      "frp_dashboard_password": "frp-dashboard-secure-2025"
    }

