apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  namespace: frp
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5sdW0udG9vbHMiOnsiYXV0aCI6ImJIVnRPbXgxYlRJd01qVT0ifX19

