apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - redis.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: platform
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: lum-tools
