apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-global-runners
  namespace: gitea
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "persistentvolumeclaims", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-global-runners
  namespace: gitea
subjects:
  - kind: ServiceAccount
    name: gitea-global-runners
    namespace: gitea
roleRef:
  kind: Role
  name: gitea-global-runners
  apiGroup: rbac.authorization.k8s.io
