apiVersion: v1
data:
  favicon.svg: |
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
      <defs>
        <linearGradient id="starGrad" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#FF8000"/>
          <stop offset="100%" style="stop-color:#E94055"/>
        </linearGradient>
      </defs>
      <path fill="url(#starGrad)" d="M50 5 L58 35 L90 35 L64 55 L74 90 L50 70 L26 90 L36 55 L10 35 L42 35 Z"/>
    </svg>
  logo.svg: |
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
      <defs>
        <linearGradient id="starGrad" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" style="stop-color:#FF8000"/>
          <stop offset="100%" style="stop-color:#E94055"/>
        </linearGradient>
      </defs>
      <path fill="url(#starGrad)" d="M50 5 L58 35 L90 35 L64 55 L74 90 L50 70 L26 90 L36 55 L10 35 L42 35 Z"/>
    </svg>
kind: ConfigMap
metadata:
  name: gitea-custom-img
  namespace: gitea
