apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lrok

resources:
  - deployment.yaml
  - namespace.yaml
  - secrets.yaml

images:
  - name: ghcr.io/luminatools/lrok
    newTag: latest
