apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: landing

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/ethanke/landing
    newTag: latest
