---
apiVersion: v1
kind: Secret
metadata:
  name: flux-system
  namespace: flux-system
stringData:
  identity: |
    -----BEGIN PRIVATE KEY-----
    MIG2AgEAMBAGByqGSM49AgEGBSuBBAAiBIGeMIGbAgEBBDBUng3QYkLPMAe/BriT
    Coqm0fKknwBDjrWnYcR52lQkZe0kzFI+N8ikazUhIpOtnl6hZANiAAQB2k7kpNOd
    evxBx95lofFWFPV6VekYMtweK1Enbu8B/oqigGx12RHsB14p64NjNAaMrMdzp23F
    VwdJiQ+UCncvPGrmEWb1llODLxGqqArwFk1ENuZQcMEv2ZhAYHqD00U=
    -----END PRIVATE KEY-----
  identity.pub: |
    ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBAHaTuSk0516/EHH3mWh8VYU9XpV6Rgy3B4rUSdu7wH+iqKAbHXZEewHXinrg2M0Boysx3OnbcVXB0mJD5QKdy88auYRZvWWU4MvEaqoCvAWTUQ25lBwwS/ZmEBgeoPTRQ==
  known_hosts: github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=

