apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/component: dns-webhook
  app.kubernetes.io/part-of: external-dns
