apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lrok

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress-lum.yaml
  - ingress-space.yaml

commonLabels:
  app.kubernetes.io/name: lrok
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: lum-tools
