apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik-metrics-scraper

resources:
  - namespace.yaml
  - rbac.yaml
  - secret.yaml
  - registry-secret.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: lum-tools
    includeSelectors: true
