apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-next-ingress
  namespace: blog-next
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/hostname: blog.lum.tools
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - blog.lum.tools
    secretName: blog-lum-tools-tls
  rules:
  - host: blog.lum.tools
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog-next-service
            port:
              number: 80
