apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-next

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secrets.yaml

images:
  - name: ghcr.io/lum-tools/blog-next
    newTag: latest
