apiVersion: v1
kind: Service
metadata:
  name: blog-next-service
  namespace: blog-next
  labels:
    app: blog-next
spec:
  type: ClusterIP
  selector:
    app: blog-next
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
